server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://47.106.70.5/store?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
      view:
        suffix: .html
mybatis-plus:
  type-aliases-package: com.example.store.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example.store.mapper: debug